language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
  yarn: true

before_install:
  - yarn install
script:
  - yarn test
  - yarn start

notifications:
  email: henninb@msn.com
git:
  autocrlf: input
