#FROM node:15.3.0-alpine
FROM node:15.3.0 as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/
RUN yarn --silent
COPY . /app
RUN yarn build

# stage 2 - build the final image and copy the react build files
FROM nginx:1.19.5-alpine
COPY --from=build /app/build /usr/share/nginx/html
# COPY --from=build /nginx.conf /etc/nginx/conf.d/default.conf
#RUN rm /etc/nginx/conf.d/default.conf
#COPY nginx/nginx.conf /etc/nginx/conf.d
CMD ["nginx", "-g", "daemon off;"]
