#!/bin/sh

git config --local user.email henninb@msn.com
git branch --set-upstream-to=origin/master master
git config --local user.name 'Brian Henning'
git config --local filter.secrets.clean "sed 's/_PASSWORD=.*/_PASSWORD=********/'"

exit 0
